### ISSUE TITLE
A formal way to include KodeView

### ISSUE THREAD

**Issue by z0xyz** [SnipMeDev/KodeView#10] opened 2023-09-12 04:11 UTC
I'm currently working on a Kotlin playground for Desktop application. I was wondering how may I include KodeView for the source code view side of the application.

**Comment by tmaxxdd** [comment] 2023-09-12 14:55
Welcome,

Thank you for a question. Some example has been added with PR #8.

So working application is under desktopExample but this library is not public ready so you must download source code and compile it on yourself.

**Comment by z0xyz** [comment] 2023-09-18 01:59
>  but this library is not public ready 
You can provide it as alpha/beta releases.
>  but this library is not public ready 
Okay thanks!

**Comment by z0xyz** [comment] 2023-09-18 05:49
Sorry about my misunderstanding. I thought KodeView works as some form of TextField but for source code (includes highlighting, linting and such). Is that on its future plans? Also I would appreciate any suggestions for such a need.

Also. I haven't been able to run it, as I'm getting the following exception
```
 $ ./gradlew run

> Task :compileKotlin
'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
By default will become an error since Gradle 8.0+! Read more: https://kotl.in/gradle/jvm/target-validation
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain


> Task :run
Gtk-Message: 08:38:54.451: Failed to load module "canberra-gtk-module"
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skia.CanvasKt._nTranslate(long, float, float)'
        at org.jetbrains.skia.CanvasKt._nTranslate(Native Method)
        at org.jetbrains.skia.CanvasKt.access$_nTranslate(Canvas.kt:1)
        at org.jetbrains.skia.Canvas.translate(Canvas.kt:1091)
        at androidx.compose.ui.graphics.SkiaBackedCanvas.translate(SkiaBackedCanvas.skiko.kt:84)
        at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:357)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:922)
        at androidx.compose.ui.platform.SkiaBasedOwner.draw(SkiaBasedOwner.skiko.kt:352)
        at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:463)
        at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:153)
        at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:152)
        at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:126)
        at androidx.compose.ui.awt.ComposeBridge.access$catchExceptions(ComposeBridge.desktop.kt:59)
        at androidx.compose.ui.awt.ComposeBridge$skikoView$1.onRender(ComposeBridge.desktop.kt:152)
        at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
        at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
        at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.redrawImmediately(LinuxOpenGLRedrawer.kt:79)
        at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.awt.kt:388)
        at androidx.compose.ui.awt.WindowComposeBridge$component$1.paint(WindowComposeBridge.desktop.kt:59)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
        at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
        at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:430)
        at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:416)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:82)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:80)
        at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:59)
        at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:55)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2300)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:471)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:234)
        at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke$performUpdate(UpdateEffect.desktop.kt:55)
        at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:64)
        at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:47)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1041)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
3 actionable tasks: 3 executed

```

**Comment by tmaxxdd** [comment] 2023-09-18 06:34
@z0xyz The library was not published yet as public as I has been preparing it for the release.

1. Now you should be able to fetch it as normal library by [Installation](https://github.com/SnipMeDev/KodeView#installation-%EF%B8%8F)

2. The CodeEditText view is pending in TODO as described in README.

3. There are some problems with running desktop examples from main, please use IntelliJ config as shown in README or try to launch Main.kt from /desktopExample/ level.

4. The logs of error you have listed are not clear to me at this moment. Please try to use newest 0.5.0 version and create new issue if this still happen.

Thanks for questions.

**Comment by tmaxxdd** [comment] 2023-09-18 06:35
The issue is closed as there is now formal way to include KodeView to project

**Closed by tmaxxdd** 2023-09-18 06:35 UTC

**Comment by z0xyz** [comment] 2023-09-18 14:59
> There are some problems with running desktop examples from main, please use IntelliJ config as shown in README or try to launch Main.kt from /desktopExample/ level.

Previously, I loaded the library into my project with `MavenLocal()`. As for  `./gradlew run` it's my actual project's gradle script wrapper . Even so, I updated to the latest version, unfortunately it still raises the same exception.

> The CodeEditText view is pending in TODO as described in README.

Hopefully I can get notified by its inclusion
